config/routes.rb
require 'resque/server'
Blog::Application.routes.draw do
  resources :microposts

  root 'home#index'

  mount Resque::Server.new, at: "/resque"

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		Resque.enqueue(Sleeper, 4)
		@a = Micropost.all
	end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :set_micropost, only: [:show, :edit, :update, :destroy]

  # GET /microposts
  # GET /microposts.json
  def index
    @microposts = Micropost.all
  end

  # GET /microposts/1
  # GET /microposts/1.json
  def show
  end

  # GET /microposts/new
  def new
    @micropost = Micropost.new
  end

  # GET /microposts/1/edit
  def edit
  end

  # POST /microposts
  # POST /microposts.json
  def create
    @micropost = Micropost.new(micropost_params)

    respond_to do |format|
      if @micropost.save
        format.html { redirect_to @micropost, notice: 'Micropost was successfully created.' }
        format.json { render action: 'show', status: :created, location: @micropost }
      else
        format.html { render action: 'new' }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /microposts/1
  # PATCH/PUT /microposts/1.json
  def update
    respond_to do |format|
      if @micropost.update(micropost_params)
        format.html { redirect_to @micropost, notice: 'Micropost was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    @micropost.destroy
    respond_to do |format|
      format.html { redirect_to microposts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micropost
      @micropost = Micropost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def micropost_params
      params.require(:micropost).permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/home/index.html.haml
.cont
	= "aaa"
	- @a.each do |a|
		= a.id
		%br

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
</body>
</html>

app/views/microposts/_form.html.haml
= form_for @micropost do |f|
  - if @micropost.errors.any?
    #error_explanation
      %h2= "#{pluralize(@micropost.errors.count, "error")} prohibited this micropost from being saved:"
      %ul
        - @micropost.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :content
    = f.text_field :content
  .actions
    = f.submit 'Save'

app/views/microposts/edit.html.haml
%h1 Editing micropost

= render 'form'

= link_to 'Show', @micropost
\|
= link_to 'Back', microposts_path

app/views/microposts/index.html.haml
%h1 Listing microposts

%table
  %thead
    %tr
      %th Content
      %th
      %th
      %th
      
  %tbody
    - @microposts.each do |micropost|
      %tr
        %td= micropost.content
        %td= link_to 'Show', micropost
        %td= link_to 'Edit', edit_micropost_path(micropost)
        %td= link_to 'Destroy', micropost, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Micropost', new_micropost_path

app/views/microposts/new.html.haml
%h1 New micropost

= render 'form'

= link_to 'Back', microposts_path

app/views/microposts/show.html.haml
%p#notice= notice

%p
  %b Content:
  = @micropost.content

= link_to 'Edit', edit_micropost_path(@micropost)
\|
= link_to 'Back', microposts_path